version: '3'

services:
  shop_api:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - shop_db

  shop_db:
    image: "postgres:14"
    env_file: .env
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "5433:5432"
    volumes:
      - 'data:/var/lib/postgresql/data'

volumes:
  data: